import HeaderPage from "./HeaderPage/HeaderPage";
import FooterPage from "./FooterPage/FooterPage";

const LayoutPages = ({ children }) => {
  return (
    <div style={{backgroundColor:"black", width:"100%",height:"100vh"}}>
      <HeaderPage />
      {children}
      {/* <div>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident, nostrum? Repudiandae eum, ad non nobis dignissimos earum amet sit officiis assumenda ab mollitia natus fugiat iure pariatur consequatur iusto sint?
        Recusandae assumenda expedita excepturi possimus, eos reiciendis aliquid dolores magnam dolorum laborum alias voluptatibus quibusdam non nulla modi? Totam sunt nisi dolorum distinctio harum perferendis provident sit corrupti voluptatibus laudantium.
        Vel, eveniet iure! Odio error porro animi vero tempora quos deleniti, debitis, sunt deserunt consectetur quidem facere ea enim cupiditate et aut. Sit quaerat cupiditate necessitatibus tempora quasi porro repellat!
        Molestias necessitatibus est quibusdam ad dolor perferendis minus obcaecati earum. Doloribus consectetur distinctio sequi quos voluptatem. Nemo repudiandae, accusamus voluptatem velit expedita facilis recusandae. Similique labore minus voluptates autem eos!
        Eius quisquam nihil deleniti laudantium laboriosam corporis ipsa sint consequatur, voluptatem tenetur atque similique officia necessitatibus natus illum, iusto nam quos. Aspernatur qui aperiam fugiat totam exercitationem possimus repudiandae consectetur?
        Consequuntur corporis nostrum aspernatur cupiditate dicta maiores libero nulla sit repellendus. Omnis eum tempore laudantium blanditiis voluptatum, quia tempora nemo aperiam eveniet labore repellat non quo, enim voluptatibus natus accusantium.
        Velit, quisquam, dicta voluptatibus sequi ad, omnis illum itaque praesentium atque soluta beatae voluptatem dolores dolorem dolor facilis laudantium. Earum velit eius a, rerum aliquam maiores? Quasi necessitatibus atque quibusdam.
        Aperiam voluptatibus beatae obcaecati voluptas repellendus tempore architecto fugiat corrupti porro, minus ipsam temporibus cumque officiis deleniti ea maxime voluptate repudiandae debitis adipisci asperiores doloribus! Quam similique assumenda suscipit illum!
        Vel consequuntur veritatis eum exercitationem fugit eligendi repudiandae quisquam, vitae, magnam dicta consectetur. Et eveniet, fugiat necessitatibus quas obcaecati modi illo ad ratione perferendis quis sunt nostrum facere quos dignissimos.
        Blanditiis maxime impedit nobis facilis quisquam temporibus maiores iste quod aliquam odit sequi fuga ut recusandae delectus, mollitia ullam quae tenetur ipsam, voluptates laboriosam? Alias fugit ipsa doloribus corrupti quam?
        Hic, atque. Deleniti quod totam veniam recusandae culpa, nam consequatur non. Ratione expedita, unde architecto debitis eaque praesentium beatae nulla vero illo blanditiis laborum mollitia cupiditate consequuntur officia ipsum quod?
        Odit labore nulla iure tempore aliquid debitis distinctio possimus eius a, laudantium suscipit reiciendis eveniet modi rem, dolor eaque rerum adipisci excepturi, sint eligendi! At voluptatibus corporis dolorem esse autem?
        Mollitia aliquam nihil delectus autem a, accusamus labore totam eveniet. Perferendis architecto magni quae, a quaerat neque consequuntur molestias doloremque quis dolorem eligendi molestiae dignissimos, iusto tempore beatae necessitatibus atque?
        Unde fuga laboriosam ex in odio inventore minima culpa quia beatae minus! Illum explicabo numquam praesentium maiores et? Ducimus obcaecati facere velit iusto molestiae quo itaque saepe ipsa praesentium tenetur!
        Blanditiis aperiam accusamus doloribus illo eos incidunt cumque iure? Reprehenderit ducimus delectus alias, iste recusandae accusantium dicta expedita distinctio assumenda doloribus, neque aliquid id veniam nulla sapiente ex totam numquam.
        Tenetur ipsum enim quaerat adipisci praesentium inventore mollitia repellendus itaque voluptate voluptatibus, quos nobis ipsam culpa provident eligendi odit molestias quibusdam sequi et non libero excepturi ea quasi. Quibusdam, earum!
        Inventore iusto alias enim facere voluptas distinctio numquam accusamus sit voluptatibus neque velit, autem quam. Architecto officiis numquam dicta temporibus ad qui odio dolore, provident quo, eaque ullam debitis aliquam.
        Nobis illum totam, ut magni distinctio facilis iure dolorum enim reiciendis quae deserunt laborum dignissimos nemo eos? Soluta nobis quia, impedit quam mollitia veniam magni, fugiat iure similique minima enim?
        Optio aspernatur eligendi velit mollitia adipisci voluptatibus, nobis officiis aperiam consequuntur atque cupiditate in, enim provident voluptatem at repudiandae reiciendis nemo dolorum voluptatum. Laudantium magni minima eius pariatur, praesentium neque.
        Et fugiat adipisci ducimus fuga nisi nulla aperiam quos numquam inventore explicabo, ea, dignissimos, quis eum ipsa. Ex ipsam, ducimus, necessitatibus odit omnis facere, quia ratione pariatur quis molestias quasi.
        Labore ullam architecto, maiores, quod, illum quo magnam veritatis porro corporis quibusdam odio iure placeat sit? A quis, nisi cupiditate, aut perspiciatis explicabo repudiandae tenetur unde, impedit quos distinctio quae.
        Ipsum corrupti aliquid eligendi tenetur sunt quia! Fugit provident quo suscipit vero libero saepe animi, deleniti nulla repellat ullam minus amet nemo rem sapiente at dolores quaerat praesentium et molestiae.
        Tempora dolorum sit quisquam. Vero ea ratione modi rerum mollitia illo maiores eligendi doloremque saepe laboriosam, atque sequi minima explicabo. Consectetur voluptatem dicta porro, vitae similique quaerat neque inventore quibusdam!
        Temporibus incidunt ab officiis minima esse alias nam atque sint omnis obcaecati, accusamus unde reiciendis ea distinctio assumenda qui optio nobis quae dicta nisi, nesciunt beatae soluta, repellat deserunt. Eaque?
        Nesciunt officia expedita eum magni quis aut reprehenderit numquam voluptate cum consequatur modi quam alias quia, amet atque itaque nostrum accusamus eos odio nulla cupiditate similique hic. Quidem, nemo cupiditate.
        Omnis aperiam ipsa temporibus veniam fugit, quidem et labore expedita? Voluptates, quo. Excepturi atque libero neque tempore dicta veniam molestias possimus cum fuga? Sequi veniam nihil, recusandae nemo veritatis voluptatum?
        Eius repellat reiciendis et vero corporis, repellendus, nisi laboriosam dicta consectetur quisquam magni recusandae iste voluptates. Odio, debitis fugiat. Temporibus, itaque! Laudantium inventore eum dolor eligendi. Ut cumque error facere.
        Natus amet, velit officiis corporis error, deserunt perspiciatis quibusdam nostrum laborum nisi distinctio perferendis illo sapiente numquam sequi incidunt asperiores nulla! Eos labore dicta amet, tempore iste excepturi nihil esse?
        Eaque sint ullam laboriosam fugit at, voluptas assumenda nostrum error molestias. Quos rerum laborum dolor voluptas assumenda id quaerat tenetur eligendi exercitationem hic, magnam blanditiis? Consequuntur voluptate nisi consequatur culpa?
        Modi rem, voluptate quas dicta debitis natus aut est facere doloremque provident ut doloribus accusantium inventore veritatis iste iure neque officiis quos magni, expedita enim. Dolores eligendi nihil cupiditate quam!
        Repudiandae pariatur quo minima. Cumque voluptate possimus voluptas numquam expedita labore illo delectus at? Dolores quibusdam harum fuga laudantium laborum, rerum enim nemo architecto molestias eaque dolor illo voluptate accusantium?
        Repudiandae ea, quo, at quos quae velit assumenda iure expedita ab dicta ratione voluptatum eveniet labore commodi voluptas libero totam? Facilis cum architecto quis eveniet quidem debitis rem, unde labore!
        Reiciendis, molestias! Libero eius eligendi similique error, pariatur ipsam unde in, explicabo quis iste doloremque, quibusdam est sit quaerat dignissimos deserunt soluta deleniti. Quod dolorem exercitationem ipsam quia, fuga error.
        Ipsam accusamus dolores nemo. Asperiores blanditiis dolorum ratione nemo, tenetur id eum molestias rem explicabo? In eligendi voluptatibus suscipit ipsa, quasi modi excepturi ut accusamus neque dolor, voluptas vitae alias.
        Non, incidunt soluta? Molestias, quam beatae cum esse ab commodi ipsum repellat inventore autem veritatis aspernatur dignissimos aliquam itaque dolorem qui. Odit repellendus cumque libero inventore ratione veniam, debitis ipsum!
        Dolor, animi illum ipsum molestias tempore fuga earum odio quidem illo dignissimos optio qui voluptatum reprehenderit sapiente doloribus nemo? Dignissimos corporis porro repudiandae, tempora dolore fugit rerum quaerat quasi praesentium.
        Tenetur facere minima dolor, illo, minus, temporibus sapiente dolorem quibusdam incidunt dicta odit. Eum placeat incidunt aperiam corrupti iste maxime. Odio reiciendis soluta repellat, autem cum animi quod ipsam et.
        Excepturi quis fuga earum repellendus dolores odit et nam expedita iste accusamus in provident, dolor molestias consequuntur dolorem quia mollitia commodi quibusdam blanditiis quasi reprehenderit similique! Sint ipsa sequi libero.
        Asperiores ut eligendi dolore saepe harum hic, culpa mollitia tenetur, consectetur, fuga quibusdam. Cum sapiente laboriosam necessitatibus illo adipisci fugit blanditiis, dicta, nam aperiam neque, exercitationem delectus facere fugiat labore.
        Sunt accusamus nihil asperiores consectetur magni libero veniam placeat dolorum omnis temporibus voluptas, repudiandae, ullam unde repellat dolorem cupiditate! Dicta omnis molestiae voluptates ratione blanditiis velit provident nobis tempore mollitia?
        Enim dignissimos sequi incidunt, natus quo dolorem, consectetur ea cum iure mollitia veritatis, perspiciatis autem modi. Id ex at nam quas quos perferendis error eos. Blanditiis sapiente aliquam asperiores ipsam.
        Repudiandae nihil consectetur iure dolorum incidunt aliquid molestias odio impedit. Consectetur autem error iusto possimus eveniet commodi cupiditate ullam ea? Asperiores eius excepturi repellendus officiis unde iste illum voluptas a.
        Voluptatem dolorem incidunt numquam repellendus facere repellat dicta, eveniet corrupti? Harum non, quidem porro animi reiciendis odio minus excepturi explicabo! Voluptatem odit quaerat alias minus eius placeat amet voluptatum quod!
        Maiores, aut eos mollitia doloribus reiciendis eligendi commodi quidem ducimus quasi, adipisci dolores dolor et cumque nemo molestias nihil quam reprehenderit sit itaque blanditiis odit doloremque dolorem? Accusamus, sequi harum?
        Nulla praesentium accusamus repellat soluta delectus numquam! Quibusdam dolorum rem nemo eveniet excepturi in praesentium tenetur eum, earum repellendus expedita consectetur repudiandae modi! Sequi nulla velit debitis tempora cumque atque?
        Nisi pariatur molestias velit, voluptatibus fugit voluptate ut, possimus repellat voluptas modi repudiandae! Nesciunt eum iste eius nostrum fugiat qui hic sit tenetur quaerat numquam veniam, nam aspernatur enim odit.
        Dolor natus laudantium ipsa exercitationem a, architecto maiores doloremque ipsam. Animi laudantium dolore sequi provident, ipsa, odit facere voluptatibus sint veniam corrupti id quaerat labore sed perferendis molestias, harum optio?
        Quia, veritatis, modi ea at sequi voluptatum iste doloremque tempora quibusdam libero, ullam impedit facere veniam fugit quasi dolore sapiente reprehenderit corporis! Beatae repudiandae delectus pariatur quisquam in veniam labore.
        Cumque natus quis dolorum perspiciatis placeat sapiente impedit voluptas numquam expedita vel enim architecto fuga beatae distinctio, optio aspernatur reiciendis fugiat amet sit quas consectetur ipsa corrupti suscipit. Nostrum, earum.
        Eum natus blanditiis itaque illo velit quaerat ipsum rem quam accusantium praesentium. Ad dolor velit autem, eveniet quos voluptas asperiores quo nulla, tenetur dicta suscipit hic non eligendi excepturi iure?
        Necessitatibus expedita consequuntur maiores sequi eius facilis suscipit illum aut doloremque laudantium obcaecati culpa nisi iusto error, aliquid neque libero, fugiat minus adipisci sit quas dolorem itaque ipsa blanditiis. Voluptatem!
        Quas modi nemo provident aliquid voluptate obcaecati, sed, sit natus architecto blanditiis explicabo! A provident eum veritatis voluptatum suscipit aspernatur, nam quae dolor nisi ullam magnam quos temporibus laborum! Ratione.
        Magnam maxime veniam qui sed ut officiis facere ratione commodi explicabo atque nulla soluta tempora architecto sunt similique amet illum distinctio, necessitatibus quod voluptates. Illum consectetur reiciendis perspiciatis expedita distinctio?
        Rerum nisi ad quae consectetur, laudantium perspiciatis deserunt obcaecati? Sunt minima sequi, aliquam voluptate nesciunt veritatis ad in blanditiis accusantium, animi quidem. Autem, amet ducimus? Aliquam eum repellat quasi nam!
        Sunt, maiores nesciunt repudiandae, nisi eum quos maxime velit sint facere odit eveniet debitis. Quaerat voluptatum, illo, eveniet, repudiandae voluptatem quisquam molestiae reiciendis praesentium necessitatibus tempore facilis eaque. Sequi, blanditiis?
        Veniam corporis consequuntur eos deserunt obcaecati magni nemo, mollitia eum nam enim animi impedit inventore eligendi! Quam molestiae reiciendis quo qui recusandae sit, voluptatem nemo ad vitae ullam, eius ducimus?
        Tempora veritatis aperiam cupiditate ad laboriosam asperiores totam magni deserunt natus, molestias distinctio ut recusandae ipsum voluptatem sequi illum? A beatae officiis mollitia neque, at quidem veniam adipisci tempora eligendi.
        Necessitatibus sequi, molestiae nesciunt praesentium libero commodi impedit esse voluptates temporibus doloribus reiciendis doloremque. Nam velit possimus laborum hic, iusto aut totam at consequuntur, iste impedit odio eius ipsam itaque!
        Eveniet veritatis exercitationem nisi debitis? Consequatur aliquid eaque placeat asperiores eveniet recusandae sit repudiandae voluptatum culpa magni iste natus veniam nulla adipisci facere libero earum, atque inventore id vero officia.
        Architecto qui sapiente porro harum! Facilis tempora dolorum eligendi nemo blanditiis dolore, nisi vitae optio ducimus quos cupiditate reiciendis explicabo aliquam veritatis rem ullam mollitia, quaerat suscipit soluta, enim dolorem.
        Quas ducimus aliquid voluptatibus quod reprehenderit. Officia nihil consequuntur illo optio quo laboriosam nesciunt sunt mollitia neque animi nisi itaque eius asperiores placeat fugiat, esse cum cumque fugit. Et, eos!
        Cupiditate accusantium optio molestias quod ab amet veritatis natus molestiae adipisci beatae asperiores, nulla praesentium ratione sapiente. Dicta voluptatibus similique voluptatum nam natus quia molestiae perspiciatis necessitatibus numquam repellendus! Velit!
        Expedita animi debitis exercitationem officiis, et rem deleniti quaerat fugiat esse quidem harum maiores ab iusto necessitatibus consectetur maxime, commodi quam est delectus voluptas vero! Ab itaque quia sit quidem!
        Dolor cupiditate doloribus modi perferendis nisi iusto. Illo velit rerum quibusdam, tempora debitis nesciunt voluptates? Quos nisi, tempora optio maiores sed provident, alias aperiam unde velit modi iure vitae sunt.
        Beatae praesentium error, ipsam deserunt pariatur aliquid doloribus totam quos ratione officia! Distinctio aliquam omnis nihil officiis sequi, hic velit ducimus excepturi similique explicabo iusto, ab, modi et eaque dignissimos.
        Nam delectus fugiat excepturi sapiente, sed nemo nihil veniam quas eum cupiditate accusantium repellendus et unde minima error maxime. Iusto dolores hic consectetur, fugiat minus error! Officiis dolore et deleniti.
        Optio ipsum minus, corporis excepturi tenetur et hic. Doloribus dignissimos enim exercitationem, eligendi perferendis, dolor dicta mollitia porro, commodi et molestias ex itaque omnis in maiores cumque earum molestiae aut!
        Facere sed quibusdam quisquam ad saepe pariatur harum fugiat sit? Asperiores laboriosam sed fugiat ad quas ut perspiciatis dolores, quaerat nemo sunt! Aspernatur vitae minus commodi natus amet quas accusamus!
        Voluptatibus facilis impedit ratione placeat nihil alias dicta officia quo animi eos dignissimos, incidunt fugit mollitia nemo veritatis vitae reprehenderit totam quisquam. Nihil tenetur voluptate nostrum? Minus itaque rem porro.
        Cupiditate, incidunt architecto. Doloribus dolore at beatae. Fugiat delectus voluptate quam autem vitae facilis et reiciendis perferendis obcaecati aliquid necessitatibus quos dolorem, nesciunt doloremque deserunt officia! Dolorum nisi voluptas amet?
        Dolor esse eos neque facere. Dolorem laboriosam nostrum quidem distinctio in iusto unde nam necessitatibus atque? Adipisci atque quis voluptatem, qui consectetur illo delectus quos rerum obcaecati repudiandae autem voluptas.
        Vel nemo nihil facilis modi totam. Modi fugit, quo vitae numquam aliquid, quos ut itaque ea deleniti rem a enim placeat odit nobis sapiente cupiditate consequatur provident tenetur quaerat ipsam.
        Magnam accusamus laborum a cumque velit. Enim recusandae adipisci fuga animi ex doloremque in natus ipsum! At debitis atque rem, recusandae temporibus ipsum quisquam obcaecati doloremque iste laborum, fugit et.
        Ullam vitae excepturi incidunt reprehenderit impedit aut. Consequuntur voluptatum voluptate suscipit excepturi cum recusandae, repellat mollitia dolorum, repellendus id aliquam possimus iusto voluptatibus blanditiis autem debitis ipsum rerum natus officiis!
        Nam rem expedita quaerat velit. Eum maxime debitis eos possimus deserunt! Magni molestiae, eum aliquid, ad non sed mollitia laudantium itaque porro assumenda tenetur illum autem error, unde nesciunt ratione!
        Natus atque ratione eaque aliquid cumque impedit possimus, fuga itaque asperiores laboriosam numquam consequatur, sint commodi maiores labore amet provident at aspernatur vero corporis! Soluta quidem est consectetur nisi alias.
        Voluptas, fugit voluptatem. Sed aliquid minima quas cumque magnam quasi minus sapiente, similique cupiditate libero harum esse quis consequuntur est dignissimos quaerat laudantium repellat incidunt? Mollitia dignissimos et minus deleniti!
        Unde iste velit voluptatibus laboriosam molestias delectus recusandae vero. Maxime, illo. Nostrum, harum eum eos nam deserunt eligendi velit iusto id nisi reiciendis minus aliquam, dolore facere? Molestiae, sunt aliquid!
        Odit sed consectetur, vero asperiores ipsa animi alias, dolorem vel, quae non neque cum. Neque accusamus iusto, molestiae praesentium animi voluptate magnam ipsum unde ducimus incidunt, cumque possimus fugiat atque!
        Velit quam suscipit asperiores harum in nisi beatae maiores ipsa dolores sequi. Necessitatibus nam dolorum repellat doloremque sit repellendus consequuntur, cum cupiditate, qui quis rerum quisquam hic? Assumenda, cupiditate modi!
        Ipsa cumque quos esse dolorem atque labore facilis ad dolore praesentium maxime vel ratione fugiat hic nulla necessitatibus veniam, placeat exercitationem modi officiis est velit tempora dolor. Illum, porro et!
        Dolores recusandae cupiditate ad quasi, doloremque possimus repellat mollitia dignissimos similique temporibus voluptatum sunt eveniet, corporis magnam? Perferendis molestias sequi amet, sed unde nobis tempora perspiciatis maxime? Neque, hic unde?
        Repudiandae in sapiente illum nemo eum ipsa similique aliquam nobis ab aperiam corporis, sunt iusto quis, explicabo ea! Culpa dolores consequuntur commodi non sint corrupti maiores alias nulla hic perferendis.
        Placeat, rem quas recusandae iusto ipsum, molestias aut perspiciatis enim voluptates nam blanditiis? Voluptates ut quidem alias esse nemo commodi, asperiores aliquam praesentium facilis labore corporis repellendus beatae optio iusto.
        Sed inventore nemo labore obcaecati ad blanditiis cumque fugit dolorem eveniet voluptatibus, suscipit molestias ducimus? Pariatur deleniti ullam iste porro illo nesciunt hic maxime tempora sed, rerum, nulla facere commodi!
        Repellendus deserunt maiores ipsum, voluptatum facilis magni voluptate reiciendis ullam earum eveniet et labore quos alias aspernatur nostrum! Dolore omnis architecto modi id cum temporibus qui. Provident aliquid obcaecati illo.
        Possimus fugiat iste vel delectus tempora quam non soluta rerum minima hic ex doloremque id odit ea, maxime perferendis. Quas molestiae ipsa fugiat voluptate asperiores hic fugit quaerat aspernatur blanditiis!
        Ipsa itaque commodi exercitationem voluptatibus dolores ipsam nihil corporis, illum blanditiis officia adipisci maxime, pariatur vero, libero quisquam velit! Laborum officiis velit eveniet quam aut eaque vel, adipisci mollitia consequatur.
        Blanditiis excepturi eum labore praesentium dicta! Suscipit illum adipisci libero? Culpa porro maxime quidem beatae voluptate quis nam sit ut architecto, non nostrum minus! Sint voluptas quisquam iusto maxime maiores.
        Tempora ducimus voluptates fugit consectetur doloribus, beatae tempore, harum nemo aut veniam nesciunt amet praesentium dolorem quo dolores qui molestias minima vero repudiandae obcaecati libero ullam! Suscipit ut praesentium harum.
        Natus soluta dolor aut laboriosam, vel repellendus. Nulla repellendus provident corporis nostrum natus exercitationem excepturi corrupti, neque officia ab repudiandae totam magnam non quia. Excepturi aperiam doloremque dolores maxime ab!
        Corrupti id, totam error reiciendis, voluptate aspernatur commodi quisquam cumque iste repellat eos, ut officiis eveniet. Alias consequatur architecto delectus eum. Quis enim laudantium ea? Autem aut tempora recusandae. Ea?
        Fugiat porro soluta, repellendus culpa ducimus at accusamus necessitatibus rerum quibusdam accusantium quod, velit sunt molestias quasi voluptas exercitationem qui officiis nostrum veniam cumque commodi temporibus earum? Fugit, ab quaerat?
        Voluptatum odio eveniet nesciunt velit. Saepe alias soluta inventore quidem, repudiandae dolore totam at neque voluptatum, in quo officia natus animi. Dolor facilis esse voluptatum consectetur id temporibus impedit nulla?
        Iure culpa maxime, officiis laudantium eos necessitatibus ad earum magni ipsa sapiente, aut velit, eveniet esse ex soluta sequi natus alias repellendus. Beatae ut officia, qui reprehenderit maiores repudiandae in?
        Delectus reiciendis dolor neque quibusdam esse non vitae, laboriosam labore sunt sit ipsum, totam laudantium? Deleniti delectus tempore, fugit quae aliquam qui consequatur enim voluptates impedit soluta, magnam pariatur veritatis.
        Incidunt officiis dicta quis nihil aperiam inventore consequuntur doloribus sunt rem fuga assumenda totam ex repellendus quaerat distinctio, nulla reprehenderit qui aut quod minima. Impedit expedita facere quo ab asperiores.
        Quis corrupti ea, sint illum a ratione et aliquam, quae cupiditate ex ad excepturi dignissimos atque obcaecati alias tempore temporibus molestias dicta! Incidunt a laboriosam maxime nihil, rerum illo deleniti!
        Sequi impedit, minima odio ab recusandae commodi magni iste voluptatem reiciendis dolorem dolor repudiandae, asperiores natus maiores, blanditiis deleniti exercitationem. Quas esse quasi minus nulla sit voluptatum odio commodi totam.
        Commodi, sapiente hic? Officia, id itaque vero animi sapiente blanditiis vitae mollitia odit est veritatis ut quos earum explicabo sit porro nostrum harum corporis. Dolores doloribus eos voluptas deleniti neque.
      </div> */}
      <FooterPage />
    </div>
  );
};

export default LayoutPages;
