import Pc1 from "/assets/images/HomePage/Products/Pc1.png";
import Pc2 from "/assets/images/HomePage/Products/Pc2.png";
import Pc3 from "/assets/images/HomePage/Products/Pc3.png";

import Rating from "/assets/images/HomePage/Products/rating.png";
//import Basket from '../public/assets/images/HomePage/Products/basket.png'
import Ms1 from "/assets/images/HomePage/Products/Ms1.png";
import Ms2 from "/assets/images/HomePage/Products/Ms2.png";
import Ms3 from "/assets/images/HomePage/Products/Ms3.png";
import Kb1 from "/assets/images/HomePage/Products/Kb1.png";
import Kb2 from "/assets/images/HomePage/Products/Kb2.png";
import Kb3 from "/assets/images/HomePage/Products/Kb3.png";

export const cards = [
  {
    id: 1,
    name: "Lenovo Legion T5 261AB790SV00BWKZ",
    price: 2500,
    image: Kb1,
    rating: Rating,
    category: "game",
    brend: "hp",
    prosessor: "Intel Core i5",
    videocard: "Nvidia",
    ram: "4 GB",
    memorytype: "SSD",
  },
  {
    id: 2,
    name: "Lenovo Legion T5 261AB790SV00BWKZ",
    price: 2500,
    image: Pc2,
    rating: Rating,
    category: "home",
    brend: "acer",
    prosessor: "AMD Ryzen 5",
    videocard: "AMD",
    ram: "8 GB",
    memorytype: "HDD",
  },
  {
    id: 3,
    name: "Lenovo Legion T5 261AB790SV00BWKZ",
    price: 2500,
    image: Pc3,
    rating: Rating,
    category: "game",
    brend: "acer",
    prosessor: "Intel Core i5",
    videocard: "Intel Graphics",
    ram: "16 GB",
    memorytype: "SSD",
  },
  {
    id: 4,
    name: "Microsoft Surface Precision Mouse",
    price: 100,
    image: Ms1,
    rating: Rating,
    category: "home",
    brend: "lenovo",
    prosessor: "Apple Silicon",
    videocard: "Nvidia",
    ram: "32 GB",
    memorytype: "HDD",
  },
  {
    id: 5,
    name: "Microsoft Surface Precision Mouse",
    price: 90,
    image: Ms2,
    rating: Rating,
    category: "game",
    brend: "toshiba",
    prosessor: "Intel Core i5",
    videocard: "AMD",
    ram: "4 GB",
    memorytype: "SSD",
  },
  {
    id: 6,
    name: "Microsoft Surface Precision Mouse",
    price: 110,
    image: Ms3,
    rating: Rating,
    category: "office",
    brend: "toshiba",
    prosessor: "Apple Silicon",
    videocard: "Intel Graphics",
    ram: "8 GB",
    memorytype: "SSD",
  },
  {
    id: 7,
    name: "Corsair K95 RGB Platinum XT",
    price: 300,
    image: Kb1,
    rating: Rating,
    category: "design",
    brend: "asus",
    prosessor: "AMD Ryzen 5",
    videocard: "Intel Graphics",
    ram: "32 GB",
    memorytype: "HDD",
  },
  {
    id: 8,
    name: "Microsoft Surface Keyboard",
    price: 250,
    image: Kb2,
    rating: Rating,
    category: "office",
    brend: "asus",
    prosessor: "Intel Core i5",
    videocard: "Nvidia",
    ram: "16 GB",
    memorytype: "SSD",
  },
  {
    id: 9,
    name: "Logitech G915 TKL Wireless Mechanical",
    price: 350,
    image: Kb3,
    rating: Rating,
    category: "design",
    brend: "hp",
    prosessor: "Apple Silicon",
    videocard: "AMD",
    ram: "4 GB",
    memorytype: "HDD",
  },
  {
    id: 10,
    name: "Razer Blade 15 Gaming Laptop",
    price: 2800,
    image: Kb1,
    rating: Rating,
    category: "game",
    brend: "razer",
    prosessor: "Intel Core i7",
    videocard: "Nvidia RTX 3080",
    ram: "16 GB",
    memorytype: "SSD",
  },
  {
    id: 11,
    name: "Apple MacBook Pro 16-inch",
    price: 3200,
    image: Pc2,
    rating: Rating,
    category: "design",
    brend: "apple",
    prosessor: "Apple M1 Max",
    videocard: "Apple GPU",
    ram: "32 GB",
    memorytype: "SSD",
  },
  {
    id: 12,
    name: "Dell XPS 13",
    price: 1800,
    image: Pc3,
    rating: Rating,
    category: "office",
    brend: "dell",
    prosessor: "Intel Core i7",
    videocard: "Intel Iris Xe",
    ram: "16 GB",
    memorytype: "SSD",
  },
  {
    id: 13,
    name: "HP Pavilion 15",
    price: 900,
    image: Kb1,
    rating: Rating,
    category: "home",
    brend: "hp",
    prosessor: "AMD Ryzen 7",
    videocard: "AMD Radeon",
    ram: "8 GB",
    memorytype: "HDD",
  },
  {
    id: 14,
    name: "Lenovo IdeaPad Gaming 3",
    price: 1200,
    image: Pc2,
    rating: Rating,
    category: "game",
    brend: "lenovo",
    prosessor: "AMD Ryzen 5",
    videocard: "Nvidia GTX 1650",
    ram: "8 GB",
    memorytype: "SSD",
  },
  {
    id: 15,
    name: "Acer Aspire 5",
    price: 600,
    image: Pc3,
    rating: Rating,
    category: "home",
    brend: "acer",
    prosessor: "Intel Core i3",
    videocard: "Intel UHD Graphics",
    ram: "4 GB",
    memorytype: "HDD",
  },
  // Additional 45 Products
  {
    id: 16,
    name: "Gigabyte AORUS 15P",
    price: 2500,
    image: Kb1,
    rating: Rating,
    category: "game",
    brend: "gigabyte",
    prosessor: "Intel Core i7",
    videocard: "Nvidia RTX 3070",
    ram: "16 GB",
    memorytype: "SSD",
  },
  {
    id: 17,
    name: "MSI GE76 Raider",
    price: 2800,
    image: Pc2,
    rating: Rating,
    category: "game",
    brend: "msi",
    prosessor: "Intel Core i9",
    videocard: "Nvidia RTX 3080",
    ram: "32 GB",
    memorytype: "SSD",
  },
  {
    id: 18,
    name: "Asus ROG Zephyrus G14",
    price: 2200,
    image: Pc3,
    rating: Rating,
    category: "game",
    brend: "asus",
    prosessor: "AMD Ryzen 9",
    videocard: "Nvidia RTX 3060",
    ram: "16 GB",
    memorytype: "SSD",
  },
  {
    id: 19,
    name: "Dell Inspiron 15 3000",
    price: 600,
    image: Kb1,
    rating: Rating,
    category: "office",
    brend: "dell",
    prosessor: "Intel Core i3",
    videocard: "Intel UHD Graphics",
    ram: "8 GB",
    memorytype: "SSD",
  },
  {
    id: 20,
    name: "Microsoft Surface Laptop 4",
    price: 1600,
    image: Pc2,
    rating: Rating,
    category: "design",
    brend: "microsoft",
    prosessor: "AMD Ryzen 7",
    videocard: "AMD Radeon",
    ram: "16 GB",
    memorytype: "SSD",
  },
  {
    id: 21,
    name: "Acer Predator Helios 300",
    price: 1900,
    image: Pc3,
    rating: Rating,
    category: "game",
    brend: "acer",
    prosessor: "Intel Core i7",
    videocard: "Nvidia RTX 3060",
    ram: "16 GB",
    memorytype: "SSD",
  },
  {
    id: 22,
    name: "HP Omen 15",
    price: 2100,
    image: Kb1,
    rating: Rating,
    category: "game",
    brend: "hp",
    prosessor: "Intel Core i7",
    videocard: "Nvidia RTX 3070",
    ram: "16 GB",
    memorytype: "SSD",
  },
  {
    id: 23,
    name: "Razer Blade Stealth 13",
    price: 1800,
    image: Pc2,
    rating: Rating,
    category: "design",
    brend: "razer",
    prosessor: "Intel Core i7",
    videocard: "Nvidia GTX 1650",
    ram: "16 GB",
    memorytype: "SSD",
  },
  {
    id: 24,
    name: "Lenovo ThinkPad X1 Carbon",
    price: 2400,
    image: Pc3,
    rating: Rating,
    category: "office",
    brend: "lenovo",
    prosessor: "Intel Core i7",
    videocard: "Intel Iris Xe",
    ram: "16 GB",
    memorytype: "SSD",
  },
  {
    id: 25,
    name: "Alienware m15 R6",
    price: 2700,
    image: Kb1,
    rating: Rating,
    category: "game",
    brend: "alienware",
    prosessor: "Intel Core i9",
    videocard: "Nvidia RTX 3080",
    ram: "32 GB",
    memorytype: "SSD",
  },
  {
    id: 26,
    name: "Samsung Galaxy Book Pro 360",
    price: 1900,
    image: Pc2,
    rating: Rating,
    category: "design",
    brend: "samsung",
    prosessor: "Intel Core i7",
    videocard: "Intel Iris Xe",
    ram: "16 GB",
    memorytype: "SSD",
  },
  {
    id: 27,
    name: "Acer Swift 3",
    price: 700,
    image: Pc3,
    rating: Rating,
    category: "home",
    brend: "acer",
    prosessor: "AMD Ryzen 5",
    videocard: "AMD Radeon",
    ram: "8 GB",
    memorytype: "SSD",
  },
  {
    id: 28,
    name: "MSI Prestige 14 Evo",
    price: 1600,
    image: Kb1,
    rating: Rating,
    category: "office",
    brend: "msi",
    prosessor: "Intel Core i7",
    videocard: "Intel Iris Xe",
    ram: "16 GB",
    memorytype: "SSD",
  },
  {
    id: 29,
    name: "Asus VivoBook 15",
    price: 600,
    image: Pc2,
    rating: Rating,
    category: "home",
    brend: "asus",
    prosessor: "Intel Core i3",
    videocard: "Intel UHD Graphics",
    ram: "8 GB",
    memorytype: "HDD",
  },
  {
    id: 30,
    name: "HP Spectre x360",
    price: 2000,
    image: Pc3,
    rating: Rating,
    category: "design",
    brend: "hp",
    prosessor: "Intel Core i7",
    videocard: "Intel Iris Xe",
    ram: "16 GB",
    memorytype: "SSD",
  },
  {
    id: 31,
    name: "Dell G5 15",
    price: 1200,
    image: Kb1,
    rating: Rating,
    category: "game",
    brend: "dell",
    prosessor: "Intel Core i7",
    videocard: "Nvidia GTX 1660 Ti",
    ram: "8 GB",
    memorytype: "SSD",
  },
  {
    id: 32,
    name: "LG Gram 17",
    price: 1800,
    image: Pc2,
    rating: Rating,
    category: "office",
    brend: "lg",
    prosessor: "Intel Core i7",
    videocard: "Intel Iris Xe",
    ram: "16 GB",
    memorytype: "SSD",
  },
  {
    id: 33,
    name: "Razer Book 13",
    price: 1600,
    image: Pc3,
    rating: Rating,
    category: "office",
    brend: "razer",
    prosessor: "Intel Core i7",
    videocard: "Intel Iris Xe",
    ram: "16 GB",
    memorytype: "SSD",
  },
  {
    id: 34,
    name: "Asus ZenBook Flip 13",
    price: 1300,
    image: Kb1,
    rating: Rating,
    category: "design",
    brend: "asus",
    prosessor: "Intel Core i5",
    videocard: "Intel Iris Xe",
    ram: "8 GB",
    memorytype: "SSD",
  },
  {
    id: 35,
    name: "Microsoft Surface Pro 7",
    price: 1500,
    image: Pc2,
    rating: Rating,
    category: "design",
    brend: "microsoft",
    prosessor: "Intel Core i5",
    videocard: "Intel Iris Plus",
    ram: "8 GB",
    memorytype: "SSD",
  },
  {
    id: 36,
    name: "HP Envy 13",
    price: 1400,
    image: Pc3,
    rating: Rating,
    category: "design",
    brend: "hp",
    prosessor: "Intel Core i7",
    videocard: "Intel Iris Xe",
    ram: "16 GB",
    memorytype: "SSD",
  },
  {
    id: 37,
    name: "Lenovo Yoga C940",
    price: 1700,
    image: Kb1,
    rating: Rating,
    category: "design",
    brend: "lenovo",
    prosessor: "Intel Core i7",
    videocard: "Intel Iris Xe",
    ram: "16 GB",
    memorytype: "SSD",
  },
  {
    id: 38,
    name: "Dell Latitude 7320",
    price: 1600,
    image: Pc2,
    rating: Rating,
    category: "office",
    brend: "dell",
    prosessor: "Intel Core i7",
    videocard: "Intel Iris Xe",
    ram: "16 GB",
    memorytype: "SSD",
  },
  {
    id: 39,
    name: "Acer Nitro 5",
    price: 1300,
    image: Pc3,
    rating: Rating,
    category: "game",
    brend: "acer",
    prosessor: "Intel Core i5",
    videocard: "Nvidia GTX 1650",
    ram: "8 GB",
    memorytype: "SSD",
  },
  {
    id: 40,
    name: "HP Elite Dragonfly",
    price: 1900,
    image: Kb1,
    rating: Rating,
    category: "office",
    brend: "hp",
    prosessor: "Intel Core i7",
    videocard: "Intel Iris Xe",
    ram: "16 GB",
    memorytype: "SSD",
  },
  {
    id: 41,
    name: "Samsung Galaxy Chromebook 2",
    price: 1200,
    image: Pc2,
    rating: Rating,
    category: "home",
    brend: "samsung",
    prosessor: "Intel Core i3",
    videocard: "Intel UHD Graphics",
    ram: "8 GB",
    memorytype: "SSD",
  },
  {
    id: 42,
    name: "Apple iMac 24-inch",
    price: 2300,
    image: Pc3,
    rating: Rating,
    category: "design",
    brend: "apple",
    prosessor: "Apple M1",
    videocard: "Apple GPU",
    ram: "16 GB",
    memorytype: "SSD",
  },
  {
    id: 43,
    name: "Dell Precision 5550",
    price: 3200,
    image: Kb1,
    rating: Rating,
    category: "design",
    brend: "dell",
    prosessor: "Intel Core i9",
    videocard: "Nvidia Quadro T2000",
    ram: "32 GB",
    memorytype: "SSD",
  },
  {
    id: 44,
    name: "HP ZBook Studio G7",
    price: 2900,
    image: Pc2,
    rating: Rating,
    category: "design",
    brend: "hp",
    prosessor: "Intel Core i9",
    videocard: "Nvidia Quadro RTX 3000",
    ram: "32 GB",
    memorytype: "SSD",
  },
  {
    id: 45,
    name: "MSI Creator Z16",
    price: 3500,
    image: Pc3,
    rating: Rating,
    category: "design",
    brend: "msi",
    prosessor: "Intel Core i9",
    videocard: "Nvidia RTX 3060",
    ram: "32 GB",
    memorytype: "SSD",
  },
  {
    id: 46,
    name: "Asus ProArt StudioBook 15",
    price: 2800,
    image: Kb1,
    rating: Rating,
    category: "design",
    brend: "asus",
    prosessor: "Intel Core i7",
    videocard: "Nvidia RTX 2060",
    ram: "16 GB",
    memorytype: "SSD",
  },
  {
    id: 47,
    name: "Lenovo Legion 5 Pro",
    price: 2200,
    image: Pc2,
    rating: Rating,
    category: "game",
    brend: "lenovo",
    prosessor: "AMD Ryzen 7",
    videocard: "Nvidia RTX 3070",
    ram: "16 GB",
    memorytype: "SSD",
  },
  {
    id: 48,
    name: "Apple MacBook Air M1",
    price: 1400,
    image: Pc3,
    rating: Rating,
    category: "office",
    brend: "apple",
    prosessor: "Apple M1",
    videocard: "Apple GPU",
    ram: "8 GB",
    memorytype: "SSD",
  },
  {
    id: 49,
    name: "HP Chromebook x360",
    price: 500,
    image: Pc1,
    rating: Rating,
    category: "home",
    brend: "hp",
    prosessor: "Intel Core i3",
    videocard: "Intel UHD Graphics",
    ram: "8 GB",
    memorytype: "SSD",
  },
  {
    id: 50,
    name: "Dell Vostro 5502",
    price: 1000,
    image: Pc2,
    rating: Rating,
    category: "office",
    brend: "dell",
    prosessor: "Intel Core i5",
    videocard: "Intel Iris Xe",
    ram: "8 GB",
    memorytype: "SSD",
  },
];
