import pcImage from "./assets/images/products/Pc1.png"
import pcImage2 from "./assets/images/products/Pc2.png"
import pcImage3 from "./assets/images/products/Pc3.png"
import ms1 from "./assets/images/products/Ms2.png"

export const products = [
  {
    id: 1,
    name: "Lenovo Legion T5 261AB790SV00BWKZ",
    price: 500,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 4.5,
    category: "game",
    brand: "hp",
    processor: "i5",
    videoCard: "Nvidia",
    ram: "4 GB",
    memoryType: "SSD",
  },
  {
    id: 2,
    name: "Lenovo Legion T5 261AB790SV00BWKZ",
    price: 400,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 3,
    category: "home",
    brand: "acer",
    processor: "AMD Ryzen 5",
    videoCard: "AMD",
    ram: "8 GB",
    memoryType: "HDD",
  },
  {
    id: 3,
    name: "Lenovo Legion T5 261AB790SV00BWKZ",
    price: 400,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 2.5,
    category: "game",
    brand: "acer",
    processor: "i5",
    videoCard: "Intel Graphics",
    ram: "16 GB",
    memoryType: "SSD",
  },
  {
    id: 4,
    name: "Microsoft Surface Precision Mouse",
    price: 400,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 4,
    category: "home",
    brand: "lenovo",
    processor: "Apple Silicon",
    videoCard: "Nvidia",
    ram: "32 GB",
    memoryType: "HDD",
  },
  {
    id: 5,
    name: "Microsoft Surface Precision Mouse",
    price: 90,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "game",
    brand: "toshiba",
    processor: "Intel Core i5",
    videoCard: "AMD",
    ram: "4 GB",
    memoryType: "SSD",
  },
  {
    id: 6,
    name: "Microsoft Surface Precision Mouse",
    price: 110,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "office",
    brand: "toshiba",
    processor: "Apple Silicon",
    videoCard: "Intel Graphics",
    ram: "8 GB",
    memoryType: "SSD",
  },
  {
    id: 7,
    name: "Corsair K95 RGB Platinum XT",
    price: 300,
   image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "design",
    brand: "asus",
    processor: "AMD Ryzen 5",
    videoCard: "Intel Graphics",
    ram: "32 GB",
    memoryType: "HDD",
  },
  {
    id: 8,
    name: "Microsoft Surface Keyboard",
    price: 250,
   image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "office",
    brand: "asus",
    processor: "Intel Core i5",
    videoCard: "Nvidia",
    ram: "16 GB",
    memoryType: "SSD",
  },
  {
    id: 9,
    name: "Logitech G915 TKL Wireless Mechanical",
    price: 350,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "design",
    brand: "hp",
    processor: "Apple Silicon",
    videoCard: "AMD",
    ram: "4 GB",
    memoryType: "HDD",
  },
  {
    id: 10,
    name: "Razer Blade 15 Gaming Laptop",
    price: 2800,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "game",
    brand: "razer",
    processor: "Intel Core i7",
    videoCard: "Nvidia RTX 3080",
    ram: "16 GB",
    memoryType: "SSD",
  },
  {
    id: 11,
    name: "Apple MacBook Pro 16-inch",
    price: 3200,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "design",
    brand: "apple",
    processor: "Apple M1 Max",
    videoCard: "Apple GPU",
    ram: "32 GB",
    memoryType: "SSD",
  },
  {
    id: 12,
    name: "Dell XPS 13",
    price: 1800,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "office",
    brand: "dell",
    processor: "Intel Core i7",
    videoCard: "Intel Iris Xe",
    ram: "16 GB",
    memoryType: "SSD",
  },
  {
    id: 13,
    name: "HP Pavilion 15",
    price: 900,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "home",
    brand: "hp",
    processor: "AMD Ryzen 7",
    videoCard: "AMD Radeon",
    ram: "8 GB",
    memoryType: "HDD",
  },
  {
    id: 14,
    name: "Lenovo IdeaPad Gaming 3",
    price: 1200,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "game",
    brand: "lenovo",
    processor: "AMD Ryzen 5",
    videoCard: "Nvidia GTX 1650",
    ram: "8 GB",
    memoryType: "SSD",
  },
  {
    id: 15,
    name: "Acer Aspire 5",
    price: 600,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "home",
    brand: "acer",
    processor: "Intel Core i3",
    videoCard: "Intel UHD Graphics",
    ram: "4 GB",
    memoryType: "HDD",
  },
  // Additional 45 Products
  {
    id: 16,
    name: "Gigabyte AORUS 15P",
    price: 2500,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "game",
    brand: "gigabyte",
    processor: "Intel Core i7",
    videoCard: "Nvidia RTX 3070",
    ram: "16 GB",
    memoryType: "SSD",
  },
  {
    id: 17,
    name: "MSI GE76 Raider",
    price: 2800,
   image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "game",
    brand: "msi",
    processor: "Intel Core i9",
    videoCard: "Nvidia RTX 3080",
    ram: "32 GB",
    memoryType: "SSD",
  },
  {
    id: 18,
    name: "Asus ROG Zephyrus G14",
    price: 2200,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "game",
    brand: "asus",
    processor: "AMD Ryzen 9",
    videoCard: "Nvidia RTX 3060",
    ram: "16 GB",
    memoryType: "SSD",
  },
  {
    id: 19,
    name: "Dell Inspiron 15 3000",
    price: 600,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "office",
    brand: "dell",
    processor: "Intel Core i3",
    videoCard: "Intel UHD Graphics",
    ram: "8 GB",
    memoryType: "SSD",
  },
  {
    id: 20,
    name: "Microsoft Surface Laptop 4",
    price: 1600,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "design",
    brand: "microsoft",
    processor: "AMD Ryzen 7",
    videoCard: "AMD Radeon",
    ram: "16 GB",
    memoryType: "SSD",
  },
  {
    id: 21,
    name: "Acer Predator Helios 300",
    price: 1900,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "game",
    brand: "acer",
    processor: "Intel Core i7",
    videoCard: "Nvidia RTX 3060",
    ram: "16 GB",
    memoryType: "SSD",
  },
  {
    id: 22,
    name: "HP Omen 15",
    price: 2100,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "game",
    brand: "hp",
    processor: "Intel Core i7",
    videoCard: "Nvidia RTX 3070",
    ram: "16 GB",
    memoryType: "SSD",
  },
  {
    id: 23,
    name: "Razer Blade Stealth 13",
    price: 1800,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "design",
    brand: "razer",
    processor: "Intel Core i7",
    videoCard: "Nvidia GTX 1650",
    ram: "16 GB",
    memoryType: "SSD",
  },
  {
    id: 24,
    name: "Lenovo ThinkPad X1 Carbon",
    price: 2400,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "office",
    brand: "lenovo",
    processor: "Intel Core i7",
    videoCard: "Intel Iris Xe",
    ram: "16 GB",
    memoryType: "SSD",
  },
  {
    id: 25,
    name: "Alienware m15 R6",
    price: 2700,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "game",
    brand: "alienware",
    processor: "Intel Core i9",
    videoCard: "Nvidia RTX 3080",
    ram: "32 GB",
    memoryType: "SSD",
  },
  {
    id: 26,
    name: "Samsung Galaxy Book Pro 360",
    price: 1900,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "design",
    brand: "samsung",
    processor: "Intel Core i7",
    videoCard: "Intel Iris Xe",
    ram: "16 GB",
    memoryType: "SSD",
  },
  {
    id: 27,
    name: "Acer Swift 3",
    price: 700,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "home",
    brand: "acer",
    processor: "AMD Ryzen 5",
    videoCard: "AMD Radeon",
    ram: "8 GB",
    memoryType: "SSD",
  },
  {
    id: 28,
    name: "MSI Prestige 14 Evo",
    price: 1600,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "office",
    brand: "msi",
    processor: "Intel Core i7",
    videoCard: "Intel Iris Xe",
    ram: "16 GB",
    memoryType: "SSD",
  },
  {
    id: 29,
    name: "Asus VivoBook 15",
    price: 600,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "home",
    brand: "asus",
    processor: "Intel Core i3",
    videoCard: "Intel UHD Graphics",
    ram: "8 GB",
    memoryType: "HDD",
  },
  {
    id: 30,
    name: "HP Spectre x360",
    price: 2000,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "design",
    brand: "hp",
    processor: "Intel Core i7",
    videoCard: "Intel Iris Xe",
    ram: "16 GB",
    memoryType: "SSD",
  },
  {
    id: 31,
    name: "Dell G5 15",
    price: 1200,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "game",
    brand: "dell",
    processor: "Intel Core i7",
    videoCard: "Nvidia GTX 1660 Ti",
    ram: "8 GB",
    memoryType: "SSD",
  },
  {
    id: 32,
    name: "LG Gram 17",
    price: 1800,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "office",
    brand: "lg",
    processor: "Intel Core i7",
    videoCard: "Intel Iris Xe",
    ram: "16 GB",
    memoryType: "SSD",
  },
  {
    id: 33,
    name: "Razer Book 13",
    price: 1600,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "office",
    brand: "razer",
    processor: "Intel Core i7",
    videoCard: "Intel Iris Xe",
    ram: "16 GB",
    memoryType: "SSD",
  },
  {
    id: 34,
    name: "Asus ZenBook Flip 13",
    price: 1300,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "design",
    brand: "asus",
    processor: "Intel Core i5",
    videoCard: "Intel Iris Xe",
    ram: "8 GB",
    memoryType: "SSD",
  },
  {
    id: 35,
    name: "Microsoft Surface Pro 7",
    price: 1500,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "design",
    brand: "microsoft",
    processor: "Intel Core i5",
    videoCard: "Intel Iris Plus",
    ram: "8 GB",
    memoryType: "SSD",
  },
  {
    id: 36,
    name: "HP Envy 13",
    price: 1400,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "design",
    brand: "hp",
    processor: "Intel Core i7",
    videoCard: "Intel Iris Xe",
    ram: "16 GB",
    memoryType: "SSD",
  },
  {
    id: 37,
    name: "Lenovo Yoga C940",
    price: 1700,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "design",
    brand: "lenovo",
    processor: "Intel Core i7",
    videoCard: "Intel Iris Xe",
    ram: "16 GB",
    memoryType: "SSD",
  },
  {
    id: 38,
    name: "Dell Latitude 7320",
    price: 1600,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "office",
    brand: "dell",
    processor: "Intel Core i7",
    videoCard: "Intel Iris Xe",
    ram: "16 GB",
    memoryType: "SSD",
  },
  {
    id: 39,
    name: "Acer Nitro 5",
    price: 1300,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "game",
    brand: "acer",
    processor: "Intel Core i5",
    videoCard: "Nvidia GTX 1650",
    ram: "8 GB",
    memoryType: "SSD",
  },
  {
    id: 40,
    name: "HP Elite Dragonfly",
    price: 1900,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "office",
    brand: "hp",
    processor: "Intel Core i7",
    videoCard: "Intel Iris Xe",
    ram: "16 GB",
    memoryType: "SSD",
  },
  {
    id: 41,
    name: "Samsung Galaxy Chromebook 2",
    price: 1200,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "home",
    brand: "samsung",
    processor: "Intel Core i3",
    videoCard: "Intel UHD Graphics",
    ram: "8 GB",
    memoryType: "SSD",
  },
  {
    id: 42,
    name: "Apple iMac 24-inch",
    price: 2300,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "design",
    brand: "apple",
    processor: "Apple M1",
    videoCard: "Apple GPU",
    ram: "16 GB",
    memoryType: "SSD",
  },
  {
    id: 43,
    name: "Dell Precision 5550",
    price: 3200,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "design",
    brand: "dell",
    processor: "Intel Core i9",
    videoCard: "Nvidia Quadro T2000",
    ram: "32 GB",
    memoryType: "SSD",
  },
  {
    id: 44,
    name: "HP ZBook Studio G7",
    price: 2900,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "design",
    brand: "hp",
    processor: "Intel Core i9",
    videoCard: "Nvidia Quadro RTX 3000",
    ram: "32 GB",
    memoryType: "SSD",
  },
  {
    id: 45,
    name: "MSI Creator Z16",
    price: 3500,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "design",
    brand: "msi",
    processor: "Intel Core i9",
    videoCard: "Nvidia RTX 3060",
    ram: "32 GB",
    memoryType: "SSD",
  },
  {
    id: 46,
    name: "Asus ProArt StudioBook 15",
    price: 2800,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "design",
    brand: "asus",
    processor: "Intel Core i7",
    videoCard: "Nvidia RTX 2060",
    ram: "16 GB",
    memoryType: "SSD",
  },
  {
    id: 47,
    name: "Lenovo Legion 5 Pro",
    price: 2200,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "game",
    brand: "lenovo",
    processor: "AMD Ryzen 7",
    videoCard: "Nvidia RTX 3070",
    ram: "16 GB",
    memoryType: "SSD",
  },
  {
    id: 48,
    name: "Apple MacBook Air M1",
    price: 1400,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "office",
    brand: "apple",
    processor: "Apple M1",
    videoCard: "Apple GPU",
    ram: "8 GB",
    memoryType: "SSD",
  },
  {
    id: 49,
    name: "HP Chromebook x360",
    price: 500,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "home",
    brand: "hp",
    processor: "Intel Core i3",
    videoCard: "Intel UHD Graphics",
    ram: "8 GB",
    memoryType: "SSD",
  },
  {
    id: 50,
    name: "Dell Vostro 5502",
    price: 1000,
    image: [pcImage,pcImage2,pcImage3,ms1],
    rating: 5,
    category: "office",
    brand: "dell",
    processor: "Intel Core i5",
    videoCard: "Intel Iris Xe",
    ram: "8 GB",
    memoryType: "SSD",
  },
];


export const queries = [
  {
    title: "Kateqoriya",
    key: "category",
    options: [
      { title: "Ev", key: "home" },
      { title: "Ofis", key: "office" },
      { title: "Oyun", key: "game" },
      { title: "Dizayn", key: "design" },
    ],
  },
  {
    title: "Brend",
    key: "brand",
    options: [
      { title: "Apple", key: "apple" },
      { title: "Asus", key: "asus" },
      { title: "Dell", key: "dell" },
      { title: "HP", key: "hp" },
      { title: "Lenovo", key: "lenovo" },
      { title: "Samsung", key: "samsung" },
      { title: "MSI", key: "msi" },
    ],
  },
  {
    title: "Prosesor",
    key: "processor",
    options: [
      { title: "Intel Core i3", key: "i3" },
      { title: "AMD Ryzen 5", key: "i5" },
      { title: "AMD Ryzen 5", key: "i5" },
      { title: "Apple Silicon", key: "applesilicon" },
    ],
  },
  {
    title: "VideoKart",
    key: "videoCard",
    options: [  
      { title: "Nvidia", key: "nvidia"},
      { title: "AMD", key: "amd"},
      { title: "Intel Graphics", key: "intelGraphics"},

    ]
  },
  {
    title: "Operativ yaddaş",
    key: "ram",
    options: [
      { title: "4 GB", key: "4gb" },
      { title: "8 GB", key: "8gb" },
      { title: "16 GB", key: "16gb" },
      { title: "32 GB", key: "32gb" },
    ],
  },
  {
    title: "Yaddaş növü",
    key: "memoryType",
    options: [
      { title: "SSD", key: "ssd" },
      { title: "HDD", key: "hdd" },
    ],
  },
  {
    title: "Əməliyyat sistemləri",
    key: "operatingSystem",
    options: [
      { title: "Windows", key: "windows" },
      { title: "macOS", key: "macos" },
      { title: "Linux", key: "linux" },

    ],
  },
  {
    title: "Ekran ölçüsü",
    key: "screenSize",
    options: [
      { title: "13-inch", key: "13inch" },
      { title: "15-inch", key: "15inch" },
    

    ],
  },
  {
    title: "Əlavə funksiyalar",
    key: "extraFunctions",
    options: [
      { title: "Touch screen", key: "touchScreen" },
      { title: "Webcam", key: "webcam" },
      { title: "Backlit keyboard", key: "backlitKeyboard" },

    

    ],
  },
 
  
]